// null, undefined
B = Boolean.prototype;
N = Number.prototype;
S = String.prototype;
A = Array.prototype;
F = Function.prototype;
O = Object.prototype;
R = RegExp.prototype;
D = Date.prototype;
M = Math.prototype;
